---
title: "Homework 2"
output: html_document
---

```{r setup, include = FALSE}
library(tidyverse)
library(caret)
library(patchwork)
library(splines)
library(gam)
library(mgcv)
library(boot)
library(ggplot2)
library(pdp)
library(earth)

set.seed(1)
```

```{r}
# Load data
college = read_csv("College.csv") %>% 
  filter(College != "Columbia University") %>% # columbia has no outstate
  select(-College)
```

# 1. Exploratory Data Analysis

```{r}
predictors = model.matrix(Outstate ~ ., college)[,-1]
response = college$Outstate

theme1 <- trellis.par.get()
theme1$plot.symbol$col <- rgb(.2, .4, .2, .5) 
theme1$plot.symbol$pch <- 16
theme1$plot.line$col <- rgb(.8, .1, .1, 1) 
theme1$plot.line$lwd <- 2
theme1$strip.background$col <- rgb(.0, .2, .6, .2)
trellis.par.set(theme1)
featurePlot(predictors, response, plot = "scatter", 
            labels = c("","Y"), type = c("p"), layout = c(4, 4))
```

# 2. Smoothing Spline

```{r}
fit.ss = smooth.spline(college$Terminal, college$Outstate)
fit.ss$df
```


```{r}
Terminallims = range(college$Terminal)
Terminal.grid = seq(from = Terminallims[1],to = Terminallims[2])

pred.ss = predict(fit.ss, x = Terminal.grid)
pred.ss.df = data.frame(pred = pred.ss$y, Terminal = Terminal.grid)

p = ggplot(data = college, aes(x = Terminal, y = Outstate)) + geom_point(color =rgb(.2, .4, .2, .5))

p + 
  geom_line(aes(x = Terminal, y = pred), data = pred.ss.df,
            color = rgb(.8, .1, .1, 1))+ theme_bw()
```

The degree of freedom obtained by generalized cross-validation is 'r fit.ss$df'. Based on the smoothing spline model, the response 'Outstate' and the predictor 'Terminal' have a non-linear relationship, but an increasing trend.

# 3. Generalized Additive Model (GAM)

```{r}
ctrl1 = trainControl(method = "cv", number = 10)
set.seed(1)
gam.fit = train(predictors, response,
                method = "gam",
                tuneGrid = data.frame(method = "GCV.Cp", select = c(TRUE,FALSE)),
                trControl = ctrl1)
gam.fit$bestTune
```

```{r}
gam.fit$finalModel
```

```{r}
gam.m1 = gam(Outstate ~ s(perc.alumni) + s(Terminal) + s(Top10perc) + s(PhD) + 
    s(Grad.Rate) + s(Books) + s(Top25perc) + s(S.F.Ratio) + s(Personal) + 
    s(P.Undergrad) + s(Enroll) + s(Room.Board) + s(Accept) + 
    s(F.Undergrad) + s(Apps) + s(Expend), data = college)

plot(gam.m1)
```

# 4. Multivariate Adaptive Regression Spline (MARS)

```{r}
mars_grid <- expand.grid(degree = 1:2,
                         nprune = 2:10)
set.seed(1)
mars.fit <- train(predictors, response, 
                  method = "earth",
                  tuneGrid = mars_grid,
                  trControl = ctrl1)

ggplot(mars.fit)
mars.fit$bestTune
coef(mars.fit$finalModel)
```

```{r}
p1 = partial(mars.fit, pred.var = c("Room.Board"), grid.resolution = 10) %>% autoplot()
p2 = partial(mars.fit, pred.var = c("F.Undergrad", "perc.alumni"), grid.resolution = 10) %>% plotPartial(levelplot = FALSE, zlab = "yhat", drape = TRUE, screen = list(z = 20, x = -60))
grid.arrange(p1, p2, ncol = 2)
```







